### ISSUE TITLE
只有文件名相同得图片才能识别

### ISSUE THREAD

**Issue by chlingm** [x-shadow-x/FaceIdentificati#1]
1、FaceCollector采集了几张头像到d:/out目录下
2、TrainData训练d:/out目录下的头像到OpenCVtrain.txt
3、根据OpenCVtrain.txt，运行TrainMain等到最新的OpenCVmodle.txt
4、找出一张一采集的图片，根据TestData生成OpenCVtest.txt
5、运行Predict()
public static void predict() throws IOException{
        System.out.println("begin");
//      String[] parg = {"OpenCVtest.txt","OpenCVtrain.txt","OpenCVresult.txt"};
        String[] parg = {"OpenCVtest.txt","OpenCVmodle.txt"};
        svm_predict.main(parg);
    }
Accuracy = 100.0% (1/1) (classification)

6、重复步骤4，并修改掉采集的图片的名字，发现预测出来的Accuracy = 0.0% (1/1) (classification)，
为什么图片的名字要一样？然道你是根据图片文件名来识别的吗？

**Comment by x-shadow-x** [comment]
不是找出一张去预测，流程应该是你获取了某个人脸的多张图片，训练得到一个模型，然后调动摄像头循环拍摄某个新的人脸，程序去预测新拍摄的人脸是否是你收集的那个特定的人脸，预测的过程中，光线那些外在因素也会影响到，并不是每次的预测结果都是对的，但因为是循环预测，所以在多次预测中只要有一次是对的，就会播放提示音乐，这就已经达到我当时的目的了，这个其实就是一个svm的二分类，即当前排到的人脸是否是我指定的人脸，是或不是
